name: playwright-alpine-release

on:
  push:
    tags: "playwright-alpine--*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Semver tag
        id: semverTag
        run: |
          tag=${GITHUB_REF_NAME#"playwright-alpine--"*}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "./playwright-alpine"
          push: true
          tags: |
            anthonylockplatform/playwright-alpine:latest
            anthonylockplatform/playwright-alpine:${{steps.semverTag.outputs.tag}}

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          notification_title: "playwright-alpine-release"
          status: ${{ job.status }}
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}
